[project]
name = "bookstore"
version = "0.1.0"
description = ""
authors = [
    {name = "Cristiano",email = "cristianosilvamolon@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "django (<5.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "faker (>=40.11.1,<41.0.0)",
    "factory-boy (>=3.3.3,<4.0.0)",
    "django-extensions (>=4.1,<5.0)",
    "django-debug-toolbar (>=6.3.0,<7.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "make (>=0.1.6.post2,<0.2.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
]

[dependency-groups]
dev = [
    "pytest (>=7,<10)",
    "pytest-django (>=4.12.0,<5.0.0)",
    "factory-boy (>=3.3.3,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
